#include "Global_variable.h"

vector<Platform> arrayofplatform;
vector <Bullet> arrayofBullet;
vector <Enemy> arrayofEnemy;
sf::RenderWindow window(sf::VideoMode(1920, 1080), "Tower Defense");
sf::Font Gamefont;
sf::Texture playerTexture;
sf::Texture bullettexture1;
sf::Texture aoetowerTexture;
sf::Texture BuffTowerTexture;
sf::Texture HealingTowerTexture;
sf::Texture HealthPotion;
sf::Texture CoinBar;
sf::Texture ScoreBar;
sf::Texture TowerBuild;
sf::Texture AttackTowerUpgrade;
sf::Texture HealingTowerUpgrade;
sf::Texture BuffTowerUpgrade;
sf::Texture AoeAttackTexture;
vector <Item> arrayofItem;
vector <Aoetower> arrayofAoetower;
vector <HealingTower>arrayofHealingtower;
vector <Bufftower> arrayofBufftower;
int playerHP = 100;
int statueHP = 30;
int wave = 0;
int playerExp = 0;
int playerLevel = 1;
int Coin = 100;
int Score = 0;
int towerType = 0;
int towerNumber = 0;
int CurrentTowerLevel = 0;
int AttackBuildCost = 100 * (arrayofAoetower.size() + 1);
int HealingBuildCost = 75 * (arrayofHealingtower.size() + 1);
int BuffBuildCost = 200 * (arrayofBufftower.size() + 1);
int AttackUpgradeCost = CurrentTowerLevel * 150;
int HealingUpgradeCost = CurrentTowerLevel * 100;
int BuffUpgradeCost = CurrentTowerLevel * 250;
int CurrentUpgradeCost;